disabled = false
weight = 1
title = "Home"

[params]
locale = "en"
label = "English"
displayName = "DK"
isoCode = "dk"
rtl = false
dateFormat = "2 January 2006"
copyright = "@2026"

[[params.author.links]]
email = "theisrud@gmail.com"

[[params.author.links]]
github = "https://github.com/Tajan92"

[[params.author.links]]
linkedin = "https://www.linkedin.com/in/theis-rud-halkj%C3%A6r-24bbaa92/"

["params.author"]
name = "Theis Rud Halkjær"
email = "theisrud@gmail.com"
headline = "Developer in progress..."
