[[main]]
name = "Blog"
pageRef = "blog"
identifier = "FZJmZdfsCc"
weight = 1

[[main]]
name = "Projects"
pageRef = "projects"
identifier = "ACeQuHByfS"
weight = 2

[[blog]]
  name = "Carport"
  pageRef = "projects/carport"
  weight = 10

[[footer]]
none = "none"
